//
//  LoginPresenter.swift
//  TesteiOSv2
//
//  Created by André Menezes on 09/03/20.
//  Copyright (c) 2020 André Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginPresentationLogic
{
//  func presentSomething(response: Login.Something.Response)
}

class LoginPresenter: LoginPresentationLogic
{
  weak var viewController: LoginDisplayLogic?
  
  // MARK: Do something
  
//  func presentSomething(response: Login.Something.Response)
//  {
//    let viewModel = Login.Something.ViewModel()
//    viewController?.displaySomething(viewModel: viewModel)
//  }
}
