//
//  LoginInteractor.swift
//  TesteiOSv2
//
//  Created by André Menezes on 09/03/20.
//  Copyright (c) 2020 André Menezes. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol LoginBusinessLogic
{
    func tryLogin(user: String, password: String)
    func allFieldsIsValid(user: String, password: String) -> Bool
}

protocol LoginDataStore
{
  //var name: String { get set }
}

class LoginInteractor: LoginBusinessLogic, LoginDataStore
{
    
    
    
    
  var presenter: LoginPresentationLogic?
  var worker: LoginWorker?
    
    func tryLogin(user: String, password: String) {
        self.worker = LoginWorker()
        self.worker?.tryLogin(user: user, password: password, success: { (user) in
            print("Nome do Usuário = \(user.name!)")
        }, failure: { (error) in
            print("Mensagem de erro = \(error.message!)")
        })
    }
    
    func allFieldsIsValid(user: String, password: String) -> Bool {
        return true
    }
}
